// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CharInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsCharInfo(buf []byte, offset flatbuffers.UOffsetT) *CharInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CharInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishCharInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCharInfo(buf []byte, offset flatbuffers.UOffsetT) *CharInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CharInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCharInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CharInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CharInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CharInfo) R() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CharInfo) MutateR(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *CharInfo) U1() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CharInfo) MutateU1(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *CharInfo) V1() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CharInfo) MutateV1(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *CharInfo) U2() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CharInfo) MutateU2(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *CharInfo) V2() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *CharInfo) MutateV2(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *CharInfo) Width() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CharInfo) MutateWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *CharInfo) Height() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CharInfo) MutateHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *CharInfo) Advance() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CharInfo) MutateAdvance(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func CharInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func CharInfoAddR(builder *flatbuffers.Builder, r int32) {
	builder.PrependInt32Slot(0, r, 0)
}
func CharInfoAddU1(builder *flatbuffers.Builder, u1 float32) {
	builder.PrependFloat32Slot(1, u1, 0.0)
}
func CharInfoAddV1(builder *flatbuffers.Builder, v1 float32) {
	builder.PrependFloat32Slot(2, v1, 0.0)
}
func CharInfoAddU2(builder *flatbuffers.Builder, u2 float32) {
	builder.PrependFloat32Slot(3, u2, 0.0)
}
func CharInfoAddV2(builder *flatbuffers.Builder, v2 float32) {
	builder.PrependFloat32Slot(4, v2, 0.0)
}
func CharInfoAddWidth(builder *flatbuffers.Builder, width int32) {
	builder.PrependInt32Slot(5, width, 0)
}
func CharInfoAddHeight(builder *flatbuffers.Builder, height int32) {
	builder.PrependInt32Slot(6, height, 0)
}
func CharInfoAddAdvance(builder *flatbuffers.Builder, advance int32) {
	builder.PrependInt32Slot(7, advance, 0)
}
func CharInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
