// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import "strconv"

type DrawCommandType int8

const (
	DrawCommandTypeDrawRoundedRect DrawCommandType = 0
	DrawCommandTypeDrawText        DrawCommandType = 1
	DrawCommandTypeFillRect        DrawCommandType = 2
	DrawCommandTypeDrawLine        DrawCommandType = 3
	DrawCommandTypeSetGlow         DrawCommandType = 4
	DrawCommandTypeSetGlass        DrawCommandType = 5
	DrawCommandTypeSetShadow       DrawCommandType = 6
	DrawCommandTypeSetOffset       DrawCommandType = 7
	DrawCommandTypeSetClip         DrawCommandType = 8
)

var EnumNamesDrawCommandType = map[DrawCommandType]string{
	DrawCommandTypeDrawRoundedRect: "DrawRoundedRect",
	DrawCommandTypeDrawText:        "DrawText",
	DrawCommandTypeFillRect:        "FillRect",
	DrawCommandTypeDrawLine:        "DrawLine",
	DrawCommandTypeSetGlow:         "SetGlow",
	DrawCommandTypeSetGlass:        "SetGlass",
	DrawCommandTypeSetShadow:       "SetShadow",
	DrawCommandTypeSetOffset:       "SetOffset",
	DrawCommandTypeSetClip:         "SetClip",
}

var EnumValuesDrawCommandType = map[string]DrawCommandType{
	"DrawRoundedRect": DrawCommandTypeDrawRoundedRect,
	"DrawText":        DrawCommandTypeDrawText,
	"FillRect":        DrawCommandTypeFillRect,
	"DrawLine":        DrawCommandTypeDrawLine,
	"SetGlow":         DrawCommandTypeSetGlow,
	"SetGlass":        DrawCommandTypeSetGlass,
	"SetShadow":       DrawCommandTypeSetShadow,
	"SetOffset":       DrawCommandTypeSetOffset,
	"SetClip":         DrawCommandTypeSetClip,
}

func (v DrawCommandType) String() string {
	if s, ok := EnumNamesDrawCommandType[v]; ok {
		return s
	}
	return "DrawCommandType(" + strconv.FormatInt(int64(v), 10) + ")"
}
