// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DrawCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsDrawCommand(buf []byte, offset flatbuffers.UOffsetT) *DrawCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DrawCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishDrawCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDrawCommand(buf []byte, offset flatbuffers.UOffsetT) *DrawCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DrawCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDrawCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DrawCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DrawCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DrawCommand) Type() DrawCommandType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return DrawCommandType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DrawCommand) MutateType(n DrawCommandType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *DrawCommand) X1() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateX1(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *DrawCommand) Y1() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateY1(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *DrawCommand) X2() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateX2(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *DrawCommand) Y2() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateY2(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *DrawCommand) W() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateW(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *DrawCommand) H() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateH(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *DrawCommand) Radius() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateRadius(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *DrawCommand) R() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateR(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *DrawCommand) G() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateG(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

func (rcv *DrawCommand) B() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateB(n byte) bool {
	return rcv._tab.MutateByteSlot(24, n)
}

func (rcv *DrawCommand) A() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DrawCommand) MutateA(n byte) bool {
	return rcv._tab.MutateByteSlot(26, n)
}

func (rcv *DrawCommand) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DrawCommand) Val1() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DrawCommand) MutateVal1(n float32) bool {
	return rcv._tab.MutateFloat32Slot(30, n)
}

func (rcv *DrawCommand) Val2() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DrawCommand) MutateVal2(n float32) bool {
	return rcv._tab.MutateFloat32Slot(32, n)
}

func (rcv *DrawCommand) Val3() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DrawCommand) MutateVal3(n float32) bool {
	return rcv._tab.MutateFloat32Slot(34, n)
}

func (rcv *DrawCommand) Flag() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DrawCommand) MutateFlag(n bool) bool {
	return rcv._tab.MutateBoolSlot(36, n)
}

func DrawCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(17)
}
func DrawCommandAddType(builder *flatbuffers.Builder, type_ DrawCommandType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func DrawCommandAddX1(builder *flatbuffers.Builder, x1 int32) {
	builder.PrependInt32Slot(1, x1, 0)
}
func DrawCommandAddY1(builder *flatbuffers.Builder, y1 int32) {
	builder.PrependInt32Slot(2, y1, 0)
}
func DrawCommandAddX2(builder *flatbuffers.Builder, x2 int32) {
	builder.PrependInt32Slot(3, x2, 0)
}
func DrawCommandAddY2(builder *flatbuffers.Builder, y2 int32) {
	builder.PrependInt32Slot(4, y2, 0)
}
func DrawCommandAddW(builder *flatbuffers.Builder, w int32) {
	builder.PrependInt32Slot(5, w, 0)
}
func DrawCommandAddH(builder *flatbuffers.Builder, h int32) {
	builder.PrependInt32Slot(6, h, 0)
}
func DrawCommandAddRadius(builder *flatbuffers.Builder, radius int32) {
	builder.PrependInt32Slot(7, radius, 0)
}
func DrawCommandAddR(builder *flatbuffers.Builder, r byte) {
	builder.PrependByteSlot(8, r, 0)
}
func DrawCommandAddG(builder *flatbuffers.Builder, g byte) {
	builder.PrependByteSlot(9, g, 0)
}
func DrawCommandAddB(builder *flatbuffers.Builder, b byte) {
	builder.PrependByteSlot(10, b, 0)
}
func DrawCommandAddA(builder *flatbuffers.Builder, a byte) {
	builder.PrependByteSlot(11, a, 0)
}
func DrawCommandAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(text), 0)
}
func DrawCommandAddVal1(builder *flatbuffers.Builder, val1 float32) {
	builder.PrependFloat32Slot(13, val1, 0.0)
}
func DrawCommandAddVal2(builder *flatbuffers.Builder, val2 float32) {
	builder.PrependFloat32Slot(14, val2, 0.0)
}
func DrawCommandAddVal3(builder *flatbuffers.Builder, val3 float32) {
	builder.PrependFloat32Slot(15, val3, 0.0)
}
func DrawCommandAddFlag(builder *flatbuffers.Builder, flag bool) {
	builder.PrependBoolSlot(16, flag, false)
}
func DrawCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
