// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Event struct {
	_tab flatbuffers.Table
}

func GetRootAsEvent(buf []byte, offset flatbuffers.UOffsetT) *Event {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Event{}
	x.Init(buf, n+offset)
	return x
}

func FinishEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEvent(buf []byte, offset flatbuffers.UOffsetT) *Event {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Event{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Event) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Event) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Event) Type() EventType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return EventType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Event) MutateType(n EventType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *Event) X() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateX(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *Event) Y() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateY(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *Event) Button() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateButton(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *Event) Delta() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateDelta(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *Event) Keycode() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateKeycode(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *Event) Char() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateChar(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *Event) Width() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *Event) Height() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func EventStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func EventAddType(builder *flatbuffers.Builder, type_ EventType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func EventAddX(builder *flatbuffers.Builder, x int32) {
	builder.PrependInt32Slot(1, x, 0)
}
func EventAddY(builder *flatbuffers.Builder, y int32) {
	builder.PrependInt32Slot(2, y, 0)
}
func EventAddButton(builder *flatbuffers.Builder, button int32) {
	builder.PrependInt32Slot(3, button, 0)
}
func EventAddDelta(builder *flatbuffers.Builder, delta int32) {
	builder.PrependInt32Slot(4, delta, 0)
}
func EventAddKeycode(builder *flatbuffers.Builder, keycode uint32) {
	builder.PrependUint32Slot(5, keycode, 0)
}
func EventAddChar(builder *flatbuffers.Builder, char uint32) {
	builder.PrependUint32Slot(6, char, 0)
}
func EventAddWidth(builder *flatbuffers.Builder, width int32) {
	builder.PrependInt32Slot(7, width, 0)
}
func EventAddHeight(builder *flatbuffers.Builder, height int32) {
	builder.PrependInt32Slot(8, height, 0)
}
func EventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
