// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import "strconv"

type EventType int8

const (
	EventTypeWindowClose EventType = 0
	EventTypeWindowSize  EventType = 1
	EventTypeMouseDown   EventType = 2
	EventTypeMouseUp     EventType = 3
	EventTypeMouseMove   EventType = 4
	EventTypeMouseWheel  EventType = 5
	EventTypeKeyDown     EventType = 6
	EventTypeKeyUp       EventType = 7
	EventTypeKeyChar     EventType = 8
)

var EnumNamesEventType = map[EventType]string{
	EventTypeWindowClose: "WindowClose",
	EventTypeWindowSize:  "WindowSize",
	EventTypeMouseDown:   "MouseDown",
	EventTypeMouseUp:     "MouseUp",
	EventTypeMouseMove:   "MouseMove",
	EventTypeMouseWheel:  "MouseWheel",
	EventTypeKeyDown:     "KeyDown",
	EventTypeKeyUp:       "KeyUp",
	EventTypeKeyChar:     "KeyChar",
}

var EnumValuesEventType = map[string]EventType{
	"WindowClose": EventTypeWindowClose,
	"WindowSize":  EventTypeWindowSize,
	"MouseDown":   EventTypeMouseDown,
	"MouseUp":     EventTypeMouseUp,
	"MouseMove":   EventTypeMouseMove,
	"MouseWheel":  EventTypeMouseWheel,
	"KeyDown":     EventTypeKeyDown,
	"KeyUp":       EventTypeKeyUp,
	"KeyChar":     EventTypeKeyChar,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
