// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EventBatch struct {
	_tab flatbuffers.Table
}

func GetRootAsEventBatch(buf []byte, offset flatbuffers.UOffsetT) *EventBatch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EventBatch{}
	x.Init(buf, n+offset)
	return x
}

func FinishEventBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEventBatch(buf []byte, offset flatbuffers.UOffsetT) *EventBatch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EventBatch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEventBatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EventBatch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EventBatch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EventBatch) Events(obj *Event, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *EventBatch) EventsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func EventBatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EventBatchAddEvents(builder *flatbuffers.Builder, events flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(events), 0)
}
func EventBatchStartEventsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EventBatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
