// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import "strconv"

type GoToRustUnion byte

const (
	GoToRustUnionNONE        GoToRustUnion = 0
	GoToRustUnionInitEngine  GoToRustUnion = 1
	GoToRustUnionRenderFrame GoToRustUnion = 2
	GoToRustUnionPlaySound   GoToRustUnion = 3
)

var EnumNamesGoToRustUnion = map[GoToRustUnion]string{
	GoToRustUnionNONE:        "NONE",
	GoToRustUnionInitEngine:  "InitEngine",
	GoToRustUnionRenderFrame: "RenderFrame",
	GoToRustUnionPlaySound:   "PlaySound",
}

var EnumValuesGoToRustUnion = map[string]GoToRustUnion{
	"NONE":        GoToRustUnionNONE,
	"InitEngine":  GoToRustUnionInitEngine,
	"RenderFrame": GoToRustUnionRenderFrame,
	"PlaySound":   GoToRustUnionPlaySound,
}

func (v GoToRustUnion) String() string {
	if s, ok := EnumNamesGoToRustUnion[v]; ok {
		return s
	}
	return "GoToRustUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
