// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GoToRustMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsGoToRustMessage(buf []byte, offset flatbuffers.UOffsetT) *GoToRustMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GoToRustMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishGoToRustMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGoToRustMessage(buf []byte, offset flatbuffers.UOffsetT) *GoToRustMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GoToRustMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGoToRustMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GoToRustMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GoToRustMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GoToRustMessage) MessageType() GoToRustUnion {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return GoToRustUnion(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GoToRustMessage) MutateMessageType(n GoToRustUnion) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *GoToRustMessage) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func GoToRustMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GoToRustMessageAddMessageType(builder *flatbuffers.Builder, messageType GoToRustUnion) {
	builder.PrependByteSlot(0, byte(messageType), 0)
}
func GoToRustMessageAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func GoToRustMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
