// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InitEngine struct {
	_tab flatbuffers.Table
}

func GetRootAsInitEngine(buf []byte, offset flatbuffers.UOffsetT) *InitEngine {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InitEngine{}
	x.Init(buf, n+offset)
	return x
}

func FinishInitEngineBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInitEngine(buf []byte, offset flatbuffers.UOffsetT) *InitEngine {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InitEngine{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInitEngineBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InitEngine) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InitEngine) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InitEngine) Width() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InitEngine) MutateWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *InitEngine) Height() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InitEngine) MutateHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *InitEngine) AtlasWidth() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InitEngine) MutateAtlasWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *InitEngine) AtlasHeight() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InitEngine) MutateAtlasHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *InitEngine) AtlasPixels(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *InitEngine) AtlasPixelsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InitEngine) AtlasPixelsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InitEngine) MutateAtlasPixels(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *InitEngine) Chars(obj *CharInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *InitEngine) CharsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func InitEngineStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func InitEngineAddWidth(builder *flatbuffers.Builder, width int32) {
	builder.PrependInt32Slot(0, width, 0)
}
func InitEngineAddHeight(builder *flatbuffers.Builder, height int32) {
	builder.PrependInt32Slot(1, height, 0)
}
func InitEngineAddAtlasWidth(builder *flatbuffers.Builder, atlasWidth int32) {
	builder.PrependInt32Slot(2, atlasWidth, 0)
}
func InitEngineAddAtlasHeight(builder *flatbuffers.Builder, atlasHeight int32) {
	builder.PrependInt32Slot(3, atlasHeight, 0)
}
func InitEngineAddAtlasPixels(builder *flatbuffers.Builder, atlasPixels flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(atlasPixels), 0)
}
func InitEngineStartAtlasPixelsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func InitEngineAddChars(builder *flatbuffers.Builder, chars flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(chars), 0)
}
func InitEngineStartCharsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InitEngineEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
