// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlaySound struct {
	_tab flatbuffers.Table
}

func GetRootAsPlaySound(buf []byte, offset flatbuffers.UOffsetT) *PlaySound {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlaySound{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlaySoundBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlaySound(buf []byte, offset flatbuffers.UOffsetT) *PlaySound {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlaySound{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlaySoundBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlaySound) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlaySound) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlaySound) Type() SoundType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return SoundType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PlaySound) MutateType(n SoundType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func PlaySoundStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlaySoundAddType(builder *flatbuffers.Builder, type_ SoundType) {
	builder.PrependInt8Slot(0, int8(type_), 0)
}
func PlaySoundEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
