// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RenderFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsRenderFrame(buf []byte, offset flatbuffers.UOffsetT) *RenderFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RenderFrame{}
	x.Init(buf, n+offset)
	return x
}

func FinishRenderFrameBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRenderFrame(buf []byte, offset flatbuffers.UOffsetT) *RenderFrame {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RenderFrame{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRenderFrameBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RenderFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RenderFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RenderFrame) Width() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RenderFrame) MutateWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *RenderFrame) Height() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RenderFrame) MutateHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *RenderFrame) Commands(obj *DrawCommand, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RenderFrame) CommandsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RenderFrame) Cursor() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RenderFrame) MutateCursor(n int8) bool {
	return rcv._tab.MutateInt8Slot(10, n)
}

func RenderFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RenderFrameAddWidth(builder *flatbuffers.Builder, width int32) {
	builder.PrependInt32Slot(0, width, 0)
}
func RenderFrameAddHeight(builder *flatbuffers.Builder, height int32) {
	builder.PrependInt32Slot(1, height, 0)
}
func RenderFrameAddCommands(builder *flatbuffers.Builder, commands flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(commands), 0)
}
func RenderFrameStartCommandsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RenderFrameAddCursor(builder *flatbuffers.Builder, cursor int8) {
	builder.PrependInt8Slot(3, cursor, 0)
}
func RenderFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
