// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RustToGoMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsRustToGoMessage(buf []byte, offset flatbuffers.UOffsetT) *RustToGoMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RustToGoMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishRustToGoMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRustToGoMessage(buf []byte, offset flatbuffers.UOffsetT) *RustToGoMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RustToGoMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRustToGoMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RustToGoMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RustToGoMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RustToGoMessage) MessageType() RustToGoUnion {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return RustToGoUnion(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RustToGoMessage) MutateMessageType(n RustToGoUnion) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *RustToGoMessage) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func RustToGoMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RustToGoMessageAddMessageType(builder *flatbuffers.Builder, messageType RustToGoUnion) {
	builder.PrependByteSlot(0, byte(messageType), 0)
}
func RustToGoMessageAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func RustToGoMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
