// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import "strconv"

type RustToGoUnion byte

const (
	RustToGoUnionNONE       RustToGoUnion = 0
	RustToGoUnionEventBatch RustToGoUnion = 1
)

var EnumNamesRustToGoUnion = map[RustToGoUnion]string{
	RustToGoUnionNONE:       "NONE",
	RustToGoUnionEventBatch: "EventBatch",
}

var EnumValuesRustToGoUnion = map[string]RustToGoUnion{
	"NONE":       RustToGoUnionNONE,
	"EventBatch": RustToGoUnionEventBatch,
}

func (v RustToGoUnion) String() string {
	if s, ok := EnumNamesRustToGoUnion[v]; ok {
		return s
	}
	return "RustToGoUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
