// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package poem

import "strconv"

type SoundType int8

const (
	SoundTypeHover   SoundType = 0
	SoundTypeClick   SoundType = 1
	SoundTypeSuccess SoundType = 2
)

var EnumNamesSoundType = map[SoundType]string{
	SoundTypeHover:   "Hover",
	SoundTypeClick:   "Click",
	SoundTypeSuccess: "Success",
}

var EnumValuesSoundType = map[string]SoundType{
	"Hover":   SoundTypeHover,
	"Click":   SoundTypeClick,
	"Success": SoundTypeSuccess,
}

func (v SoundType) String() string {
	if s, ok := EnumNamesSoundType[v]; ok {
		return s
	}
	return "SoundType(" + strconv.FormatInt(int64(v), 10) + ")"
}
