package web

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"net/http"
)

// Generated by scripts/build_web_cartography.ps1 from the pinned Go toolchain
// and the shared cartography command.
//
//go:embed vector-assets/cartography.wasm
var cartographyWASM []byte

//go:embed vector-assets/wasm_exec.js
var wasmExecScript []byte

//go:embed vector-assets/map-worker.js
var mapWorkerScript []byte

// vectorAssetVersion changes whenever any part of the browser cartography
// runtime changes. The page passes it to the viewport script, which propagates
// it to the worker, Go WASM runtime, and cartography module. This lets every
// response remain immutable without serving a mixed generation from cache.
var vectorAssetVersion = func() string {
	hash := sha256.New()
	for _, asset := range [][]byte{mapViewportScript, mapWorkerScript, wasmExecScript, cartographyWASM} {
		_, _ = hash.Write(asset)
	}
	return hex.EncodeToString(hash.Sum(nil)[:8])
}()

func immutableVectorAsset(contentType string, body []byte) http.HandlerFunc {
	return func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", contentType)
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		_, _ = w.Write(body)
	}
}
