// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod poem {

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_DRAW_COMMAND_TYPE: i8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_DRAW_COMMAND_TYPE: i8 = 8;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_DRAW_COMMAND_TYPE: [DrawCommandType; 9] = [
        DrawCommandType::DrawRoundedRect,
        DrawCommandType::DrawText,
        DrawCommandType::FillRect,
        DrawCommandType::DrawLine,
        DrawCommandType::SetGlow,
        DrawCommandType::SetGlass,
        DrawCommandType::SetShadow,
        DrawCommandType::SetOffset,
        DrawCommandType::SetClip,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct DrawCommandType(pub i8);
    #[allow(non_upper_case_globals)]
    impl DrawCommandType {
        pub const DrawRoundedRect: Self = Self(0);
        pub const DrawText: Self = Self(1);
        pub const FillRect: Self = Self(2);
        pub const DrawLine: Self = Self(3);
        pub const SetGlow: Self = Self(4);
        pub const SetGlass: Self = Self(5);
        pub const SetShadow: Self = Self(6);
        pub const SetOffset: Self = Self(7);
        pub const SetClip: Self = Self(8);

        pub const ENUM_MIN: i8 = 0;
        pub const ENUM_MAX: i8 = 8;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::DrawRoundedRect,
            Self::DrawText,
            Self::FillRect,
            Self::DrawLine,
            Self::SetGlow,
            Self::SetGlass,
            Self::SetShadow,
            Self::SetOffset,
            Self::SetClip,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::DrawRoundedRect => Some("DrawRoundedRect"),
                Self::DrawText => Some("DrawText"),
                Self::FillRect => Some("FillRect"),
                Self::DrawLine => Some("DrawLine"),
                Self::SetGlow => Some("SetGlow"),
                Self::SetGlass => Some("SetGlass"),
                Self::SetShadow => Some("SetShadow"),
                Self::SetOffset => Some("SetOffset"),
                Self::SetClip => Some("SetClip"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for DrawCommandType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for DrawCommandType {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for DrawCommandType {
        type Output = DrawCommandType;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for DrawCommandType {
        type Scalar = i8;
        #[inline]
        fn to_little_endian(self) -> i8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: i8) -> Self {
            let b = i8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for DrawCommandType {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            i8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for DrawCommandType {}
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_SOUND_TYPE: i8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_SOUND_TYPE: i8 = 2;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_SOUND_TYPE: [SoundType; 3] =
        [SoundType::Hover, SoundType::Click, SoundType::Success];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct SoundType(pub i8);
    #[allow(non_upper_case_globals)]
    impl SoundType {
        pub const Hover: Self = Self(0);
        pub const Click: Self = Self(1);
        pub const Success: Self = Self(2);

        pub const ENUM_MIN: i8 = 0;
        pub const ENUM_MAX: i8 = 2;
        pub const ENUM_VALUES: &'static [Self] = &[Self::Hover, Self::Click, Self::Success];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::Hover => Some("Hover"),
                Self::Click => Some("Click"),
                Self::Success => Some("Success"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for SoundType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for SoundType {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for SoundType {
        type Output = SoundType;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for SoundType {
        type Scalar = i8;
        #[inline]
        fn to_little_endian(self) -> i8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: i8) -> Self {
            let b = i8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for SoundType {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            i8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for SoundType {}
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_GO_TO_RUST_UNION: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_GO_TO_RUST_UNION: u8 = 3;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_GO_TO_RUST_UNION: [GoToRustUnion; 4] = [
        GoToRustUnion::NONE,
        GoToRustUnion::InitEngine,
        GoToRustUnion::RenderFrame,
        GoToRustUnion::PlaySound,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct GoToRustUnion(pub u8);
    #[allow(non_upper_case_globals)]
    impl GoToRustUnion {
        pub const NONE: Self = Self(0);
        pub const InitEngine: Self = Self(1);
        pub const RenderFrame: Self = Self(2);
        pub const PlaySound: Self = Self(3);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 3;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::NONE,
            Self::InitEngine,
            Self::RenderFrame,
            Self::PlaySound,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::NONE => Some("NONE"),
                Self::InitEngine => Some("InitEngine"),
                Self::RenderFrame => Some("RenderFrame"),
                Self::PlaySound => Some("PlaySound"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for GoToRustUnion {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for GoToRustUnion {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for GoToRustUnion {
        type Output = GoToRustUnion;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for GoToRustUnion {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for GoToRustUnion {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            u8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for GoToRustUnion {}
    pub struct GoToRustUnionUnionTableOffset {}

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_EVENT_TYPE: i8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_EVENT_TYPE: i8 = 8;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_EVENT_TYPE: [EventType; 9] = [
        EventType::WindowClose,
        EventType::WindowSize,
        EventType::MouseDown,
        EventType::MouseUp,
        EventType::MouseMove,
        EventType::MouseWheel,
        EventType::KeyDown,
        EventType::KeyUp,
        EventType::KeyChar,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct EventType(pub i8);
    #[allow(non_upper_case_globals)]
    impl EventType {
        pub const WindowClose: Self = Self(0);
        pub const WindowSize: Self = Self(1);
        pub const MouseDown: Self = Self(2);
        pub const MouseUp: Self = Self(3);
        pub const MouseMove: Self = Self(4);
        pub const MouseWheel: Self = Self(5);
        pub const KeyDown: Self = Self(6);
        pub const KeyUp: Self = Self(7);
        pub const KeyChar: Self = Self(8);

        pub const ENUM_MIN: i8 = 0;
        pub const ENUM_MAX: i8 = 8;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::WindowClose,
            Self::WindowSize,
            Self::MouseDown,
            Self::MouseUp,
            Self::MouseMove,
            Self::MouseWheel,
            Self::KeyDown,
            Self::KeyUp,
            Self::KeyChar,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::WindowClose => Some("WindowClose"),
                Self::WindowSize => Some("WindowSize"),
                Self::MouseDown => Some("MouseDown"),
                Self::MouseUp => Some("MouseUp"),
                Self::MouseMove => Some("MouseMove"),
                Self::MouseWheel => Some("MouseWheel"),
                Self::KeyDown => Some("KeyDown"),
                Self::KeyUp => Some("KeyUp"),
                Self::KeyChar => Some("KeyChar"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for EventType {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for EventType {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for EventType {
        type Output = EventType;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for EventType {
        type Scalar = i8;
        #[inline]
        fn to_little_endian(self) -> i8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: i8) -> Self {
            let b = i8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for EventType {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            i8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for EventType {}
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_RUST_TO_GO_UNION: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_RUST_TO_GO_UNION: u8 = 1;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_RUST_TO_GO_UNION: [RustToGoUnion; 2] =
        [RustToGoUnion::NONE, RustToGoUnion::EventBatch];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct RustToGoUnion(pub u8);
    #[allow(non_upper_case_globals)]
    impl RustToGoUnion {
        pub const NONE: Self = Self(0);
        pub const EventBatch: Self = Self(1);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 1;
        pub const ENUM_VALUES: &'static [Self] = &[Self::NONE, Self::EventBatch];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::NONE => Some("NONE"),
                Self::EventBatch => Some("EventBatch"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for RustToGoUnion {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for RustToGoUnion {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for RustToGoUnion {
        type Output = RustToGoUnion;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for RustToGoUnion {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for RustToGoUnion {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            u8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for RustToGoUnion {}
    pub struct RustToGoUnionUnionTableOffset {}

    pub enum DrawCommandOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct DrawCommand<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for DrawCommand<'a> {
        type Inner = DrawCommand<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> DrawCommand<'a> {
        pub const VT_TYPE_: ::flatbuffers::VOffsetT = 4;
        pub const VT_X1: ::flatbuffers::VOffsetT = 6;
        pub const VT_Y1: ::flatbuffers::VOffsetT = 8;
        pub const VT_X2: ::flatbuffers::VOffsetT = 10;
        pub const VT_Y2: ::flatbuffers::VOffsetT = 12;
        pub const VT_W: ::flatbuffers::VOffsetT = 14;
        pub const VT_H: ::flatbuffers::VOffsetT = 16;
        pub const VT_RADIUS: ::flatbuffers::VOffsetT = 18;
        pub const VT_R: ::flatbuffers::VOffsetT = 20;
        pub const VT_G: ::flatbuffers::VOffsetT = 22;
        pub const VT_B: ::flatbuffers::VOffsetT = 24;
        pub const VT_A: ::flatbuffers::VOffsetT = 26;
        pub const VT_TEXT: ::flatbuffers::VOffsetT = 28;
        pub const VT_VAL1: ::flatbuffers::VOffsetT = 30;
        pub const VT_VAL2: ::flatbuffers::VOffsetT = 32;
        pub const VT_VAL3: ::flatbuffers::VOffsetT = 34;
        pub const VT_FLAG: ::flatbuffers::VOffsetT = 36;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            DrawCommand { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args DrawCommandArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<DrawCommand<'bldr>> {
            let mut builder = DrawCommandBuilder::new(_fbb);
            builder.add_val3(args.val3);
            builder.add_val2(args.val2);
            builder.add_val1(args.val1);
            if let Some(x) = args.text {
                builder.add_text(x);
            }
            builder.add_radius(args.radius);
            builder.add_h(args.h);
            builder.add_w(args.w);
            builder.add_y2(args.y2);
            builder.add_x2(args.x2);
            builder.add_y1(args.y1);
            builder.add_x1(args.x1);
            builder.add_flag(args.flag);
            builder.add_a(args.a);
            builder.add_b(args.b);
            builder.add_g(args.g);
            builder.add_r(args.r);
            builder.add_type_(args.type_);
            builder.finish()
        }

        #[inline]
        pub fn type_(&self) -> DrawCommandType {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<DrawCommandType>(
                        DrawCommand::VT_TYPE_,
                        Some(DrawCommandType::DrawRoundedRect),
                    )
                    .unwrap()
            }
        }
        #[inline]
        pub fn x1(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(DrawCommand::VT_X1, Some(0)).unwrap() }
        }
        #[inline]
        pub fn y1(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(DrawCommand::VT_Y1, Some(0)).unwrap() }
        }
        #[inline]
        pub fn x2(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(DrawCommand::VT_X2, Some(0)).unwrap() }
        }
        #[inline]
        pub fn y2(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(DrawCommand::VT_Y2, Some(0)).unwrap() }
        }
        #[inline]
        pub fn w(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(DrawCommand::VT_W, Some(0)).unwrap() }
        }
        #[inline]
        pub fn h(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(DrawCommand::VT_H, Some(0)).unwrap() }
        }
        #[inline]
        pub fn radius(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<i32>(DrawCommand::VT_RADIUS, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn r(&self) -> u8 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u8>(DrawCommand::VT_R, Some(0)).unwrap() }
        }
        #[inline]
        pub fn g(&self) -> u8 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u8>(DrawCommand::VT_G, Some(0)).unwrap() }
        }
        #[inline]
        pub fn b(&self) -> u8 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u8>(DrawCommand::VT_B, Some(0)).unwrap() }
        }
        #[inline]
        pub fn a(&self) -> u8 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u8>(DrawCommand::VT_A, Some(0)).unwrap() }
        }
        #[inline]
        pub fn text(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(DrawCommand::VT_TEXT, None)
            }
        }
        #[inline]
        pub fn val1(&self) -> f32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<f32>(DrawCommand::VT_VAL1, Some(0.0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn val2(&self) -> f32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<f32>(DrawCommand::VT_VAL2, Some(0.0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn val3(&self) -> f32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<f32>(DrawCommand::VT_VAL3, Some(0.0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn flag(&self) -> bool {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<bool>(DrawCommand::VT_FLAG, Some(false))
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for DrawCommand<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<DrawCommandType>("type_", Self::VT_TYPE_, false)?
                .visit_field::<i32>("x1", Self::VT_X1, false)?
                .visit_field::<i32>("y1", Self::VT_Y1, false)?
                .visit_field::<i32>("x2", Self::VT_X2, false)?
                .visit_field::<i32>("y2", Self::VT_Y2, false)?
                .visit_field::<i32>("w", Self::VT_W, false)?
                .visit_field::<i32>("h", Self::VT_H, false)?
                .visit_field::<i32>("radius", Self::VT_RADIUS, false)?
                .visit_field::<u8>("r", Self::VT_R, false)?
                .visit_field::<u8>("g", Self::VT_G, false)?
                .visit_field::<u8>("b", Self::VT_B, false)?
                .visit_field::<u8>("a", Self::VT_A, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, false)?
                .visit_field::<f32>("val1", Self::VT_VAL1, false)?
                .visit_field::<f32>("val2", Self::VT_VAL2, false)?
                .visit_field::<f32>("val3", Self::VT_VAL3, false)?
                .visit_field::<bool>("flag", Self::VT_FLAG, false)?
                .finish();
            Ok(())
        }
    }
    pub struct DrawCommandArgs<'a> {
        pub type_: DrawCommandType,
        pub x1: i32,
        pub y1: i32,
        pub x2: i32,
        pub y2: i32,
        pub w: i32,
        pub h: i32,
        pub radius: i32,
        pub r: u8,
        pub g: u8,
        pub b: u8,
        pub a: u8,
        pub text: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub val1: f32,
        pub val2: f32,
        pub val3: f32,
        pub flag: bool,
    }
    impl<'a> Default for DrawCommandArgs<'a> {
        #[inline]
        fn default() -> Self {
            DrawCommandArgs {
                type_: DrawCommandType::DrawRoundedRect,
                x1: 0,
                y1: 0,
                x2: 0,
                y2: 0,
                w: 0,
                h: 0,
                radius: 0,
                r: 0,
                g: 0,
                b: 0,
                a: 0,
                text: None,
                val1: 0.0,
                val2: 0.0,
                val3: 0.0,
                flag: false,
            }
        }
    }

    pub struct DrawCommandBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DrawCommandBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_type_(&mut self, type_: DrawCommandType) {
            self.fbb_.push_slot::<DrawCommandType>(
                DrawCommand::VT_TYPE_,
                type_,
                DrawCommandType::DrawRoundedRect,
            );
        }
        #[inline]
        pub fn add_x1(&mut self, x1: i32) {
            self.fbb_.push_slot::<i32>(DrawCommand::VT_X1, x1, 0);
        }
        #[inline]
        pub fn add_y1(&mut self, y1: i32) {
            self.fbb_.push_slot::<i32>(DrawCommand::VT_Y1, y1, 0);
        }
        #[inline]
        pub fn add_x2(&mut self, x2: i32) {
            self.fbb_.push_slot::<i32>(DrawCommand::VT_X2, x2, 0);
        }
        #[inline]
        pub fn add_y2(&mut self, y2: i32) {
            self.fbb_.push_slot::<i32>(DrawCommand::VT_Y2, y2, 0);
        }
        #[inline]
        pub fn add_w(&mut self, w: i32) {
            self.fbb_.push_slot::<i32>(DrawCommand::VT_W, w, 0);
        }
        #[inline]
        pub fn add_h(&mut self, h: i32) {
            self.fbb_.push_slot::<i32>(DrawCommand::VT_H, h, 0);
        }
        #[inline]
        pub fn add_radius(&mut self, radius: i32) {
            self.fbb_
                .push_slot::<i32>(DrawCommand::VT_RADIUS, radius, 0);
        }
        #[inline]
        pub fn add_r(&mut self, r: u8) {
            self.fbb_.push_slot::<u8>(DrawCommand::VT_R, r, 0);
        }
        #[inline]
        pub fn add_g(&mut self, g: u8) {
            self.fbb_.push_slot::<u8>(DrawCommand::VT_G, g, 0);
        }
        #[inline]
        pub fn add_b(&mut self, b: u8) {
            self.fbb_.push_slot::<u8>(DrawCommand::VT_B, b, 0);
        }
        #[inline]
        pub fn add_a(&mut self, a: u8) {
            self.fbb_.push_slot::<u8>(DrawCommand::VT_A, a, 0);
        }
        #[inline]
        pub fn add_text(&mut self, text: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(DrawCommand::VT_TEXT, text);
        }
        #[inline]
        pub fn add_val1(&mut self, val1: f32) {
            self.fbb_.push_slot::<f32>(DrawCommand::VT_VAL1, val1, 0.0);
        }
        #[inline]
        pub fn add_val2(&mut self, val2: f32) {
            self.fbb_.push_slot::<f32>(DrawCommand::VT_VAL2, val2, 0.0);
        }
        #[inline]
        pub fn add_val3(&mut self, val3: f32) {
            self.fbb_.push_slot::<f32>(DrawCommand::VT_VAL3, val3, 0.0);
        }
        #[inline]
        pub fn add_flag(&mut self, flag: bool) {
            self.fbb_
                .push_slot::<bool>(DrawCommand::VT_FLAG, flag, false);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> DrawCommandBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            DrawCommandBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<DrawCommand<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for DrawCommand<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("DrawCommand");
            ds.field("type_", &self.type_());
            ds.field("x1", &self.x1());
            ds.field("y1", &self.y1());
            ds.field("x2", &self.x2());
            ds.field("y2", &self.y2());
            ds.field("w", &self.w());
            ds.field("h", &self.h());
            ds.field("radius", &self.radius());
            ds.field("r", &self.r());
            ds.field("g", &self.g());
            ds.field("b", &self.b());
            ds.field("a", &self.a());
            ds.field("text", &self.text());
            ds.field("val1", &self.val1());
            ds.field("val2", &self.val2());
            ds.field("val3", &self.val3());
            ds.field("flag", &self.flag());
            ds.finish()
        }
    }
    pub enum RenderFrameOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct RenderFrame<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for RenderFrame<'a> {
        type Inner = RenderFrame<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> RenderFrame<'a> {
        pub const VT_WIDTH: ::flatbuffers::VOffsetT = 4;
        pub const VT_HEIGHT: ::flatbuffers::VOffsetT = 6;
        pub const VT_COMMANDS: ::flatbuffers::VOffsetT = 8;
        pub const VT_CURSOR: ::flatbuffers::VOffsetT = 10;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            RenderFrame { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args RenderFrameArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<RenderFrame<'bldr>> {
            let mut builder = RenderFrameBuilder::new(_fbb);
            if let Some(x) = args.commands {
                builder.add_commands(x);
            }
            builder.add_height(args.height);
            builder.add_width(args.width);
            builder.add_cursor(args.cursor);
            builder.finish()
        }

        #[inline]
        pub fn width(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<i32>(RenderFrame::VT_WIDTH, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn height(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<i32>(RenderFrame::VT_HEIGHT, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn commands(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DrawCommand<'a>>>>
        {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DrawCommand>>,
                >>(RenderFrame::VT_COMMANDS, None)
            }
        }
        #[inline]
        pub fn cursor(&self) -> i8 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<i8>(RenderFrame::VT_CURSOR, Some(0))
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for RenderFrame<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<i32>("width", Self::VT_WIDTH, false)?
                .visit_field::<i32>("height", Self::VT_HEIGHT, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<DrawCommand>>,
                >>("commands", Self::VT_COMMANDS, false)?
                .visit_field::<i8>("cursor", Self::VT_CURSOR, false)?
                .finish();
            Ok(())
        }
    }
    pub struct RenderFrameArgs<'a> {
        pub width: i32,
        pub height: i32,
        pub commands: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DrawCommand<'a>>>,
            >,
        >,
        pub cursor: i8,
    }
    impl<'a> Default for RenderFrameArgs<'a> {
        #[inline]
        fn default() -> Self {
            RenderFrameArgs {
                width: 0,
                height: 0,
                commands: None,
                cursor: 0,
            }
        }
    }

    pub struct RenderFrameBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RenderFrameBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_width(&mut self, width: i32) {
            self.fbb_.push_slot::<i32>(RenderFrame::VT_WIDTH, width, 0);
        }
        #[inline]
        pub fn add_height(&mut self, height: i32) {
            self.fbb_
                .push_slot::<i32>(RenderFrame::VT_HEIGHT, height, 0);
        }
        #[inline]
        pub fn add_commands(
            &mut self,
            commands: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<DrawCommand<'b>>>,
            >,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                RenderFrame::VT_COMMANDS,
                commands,
            );
        }
        #[inline]
        pub fn add_cursor(&mut self, cursor: i8) {
            self.fbb_.push_slot::<i8>(RenderFrame::VT_CURSOR, cursor, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> RenderFrameBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            RenderFrameBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<RenderFrame<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for RenderFrame<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("RenderFrame");
            ds.field("width", &self.width());
            ds.field("height", &self.height());
            ds.field("commands", &self.commands());
            ds.field("cursor", &self.cursor());
            ds.finish()
        }
    }
    pub enum PlaySoundOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct PlaySound<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for PlaySound<'a> {
        type Inner = PlaySound<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> PlaySound<'a> {
        pub const VT_TYPE_: ::flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            PlaySound { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args PlaySoundArgs,
        ) -> ::flatbuffers::WIPOffset<PlaySound<'bldr>> {
            let mut builder = PlaySoundBuilder::new(_fbb);
            builder.add_type_(args.type_);
            builder.finish()
        }

        #[inline]
        pub fn type_(&self) -> SoundType {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<SoundType>(PlaySound::VT_TYPE_, Some(SoundType::Hover))
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for PlaySound<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<SoundType>("type_", Self::VT_TYPE_, false)?
                .finish();
            Ok(())
        }
    }
    pub struct PlaySoundArgs {
        pub type_: SoundType,
    }
    impl<'a> Default for PlaySoundArgs {
        #[inline]
        fn default() -> Self {
            PlaySoundArgs {
                type_: SoundType::Hover,
            }
        }
    }

    pub struct PlaySoundBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PlaySoundBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_type_(&mut self, type_: SoundType) {
            self.fbb_
                .push_slot::<SoundType>(PlaySound::VT_TYPE_, type_, SoundType::Hover);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> PlaySoundBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            PlaySoundBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<PlaySound<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for PlaySound<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("PlaySound");
            ds.field("type_", &self.type_());
            ds.finish()
        }
    }
    pub enum CharInfoOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct CharInfo<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for CharInfo<'a> {
        type Inner = CharInfo<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> CharInfo<'a> {
        pub const VT_R: ::flatbuffers::VOffsetT = 4;
        pub const VT_U1: ::flatbuffers::VOffsetT = 6;
        pub const VT_V1: ::flatbuffers::VOffsetT = 8;
        pub const VT_U2: ::flatbuffers::VOffsetT = 10;
        pub const VT_V2: ::flatbuffers::VOffsetT = 12;
        pub const VT_WIDTH: ::flatbuffers::VOffsetT = 14;
        pub const VT_HEIGHT: ::flatbuffers::VOffsetT = 16;
        pub const VT_ADVANCE: ::flatbuffers::VOffsetT = 18;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            CharInfo { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args CharInfoArgs,
        ) -> ::flatbuffers::WIPOffset<CharInfo<'bldr>> {
            let mut builder = CharInfoBuilder::new(_fbb);
            builder.add_advance(args.advance);
            builder.add_height(args.height);
            builder.add_width(args.width);
            builder.add_v2(args.v2);
            builder.add_u2(args.u2);
            builder.add_v1(args.v1);
            builder.add_u1(args.u1);
            builder.add_r(args.r);
            builder.finish()
        }

        #[inline]
        pub fn r(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(CharInfo::VT_R, Some(0)).unwrap() }
        }
        #[inline]
        pub fn u1(&self) -> f32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<f32>(CharInfo::VT_U1, Some(0.0)).unwrap() }
        }
        #[inline]
        pub fn v1(&self) -> f32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<f32>(CharInfo::VT_V1, Some(0.0)).unwrap() }
        }
        #[inline]
        pub fn u2(&self) -> f32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<f32>(CharInfo::VT_U2, Some(0.0)).unwrap() }
        }
        #[inline]
        pub fn v2(&self) -> f32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<f32>(CharInfo::VT_V2, Some(0.0)).unwrap() }
        }
        #[inline]
        pub fn width(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(CharInfo::VT_WIDTH, Some(0)).unwrap() }
        }
        #[inline]
        pub fn height(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(CharInfo::VT_HEIGHT, Some(0)).unwrap() }
        }
        #[inline]
        pub fn advance(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(CharInfo::VT_ADVANCE, Some(0)).unwrap() }
        }
    }

    impl ::flatbuffers::Verifiable for CharInfo<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<i32>("r", Self::VT_R, false)?
                .visit_field::<f32>("u1", Self::VT_U1, false)?
                .visit_field::<f32>("v1", Self::VT_V1, false)?
                .visit_field::<f32>("u2", Self::VT_U2, false)?
                .visit_field::<f32>("v2", Self::VT_V2, false)?
                .visit_field::<i32>("width", Self::VT_WIDTH, false)?
                .visit_field::<i32>("height", Self::VT_HEIGHT, false)?
                .visit_field::<i32>("advance", Self::VT_ADVANCE, false)?
                .finish();
            Ok(())
        }
    }
    pub struct CharInfoArgs {
        pub r: i32,
        pub u1: f32,
        pub v1: f32,
        pub u2: f32,
        pub v2: f32,
        pub width: i32,
        pub height: i32,
        pub advance: i32,
    }
    impl<'a> Default for CharInfoArgs {
        #[inline]
        fn default() -> Self {
            CharInfoArgs {
                r: 0,
                u1: 0.0,
                v1: 0.0,
                u2: 0.0,
                v2: 0.0,
                width: 0,
                height: 0,
                advance: 0,
            }
        }
    }

    pub struct CharInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CharInfoBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_r(&mut self, r: i32) {
            self.fbb_.push_slot::<i32>(CharInfo::VT_R, r, 0);
        }
        #[inline]
        pub fn add_u1(&mut self, u1: f32) {
            self.fbb_.push_slot::<f32>(CharInfo::VT_U1, u1, 0.0);
        }
        #[inline]
        pub fn add_v1(&mut self, v1: f32) {
            self.fbb_.push_slot::<f32>(CharInfo::VT_V1, v1, 0.0);
        }
        #[inline]
        pub fn add_u2(&mut self, u2: f32) {
            self.fbb_.push_slot::<f32>(CharInfo::VT_U2, u2, 0.0);
        }
        #[inline]
        pub fn add_v2(&mut self, v2: f32) {
            self.fbb_.push_slot::<f32>(CharInfo::VT_V2, v2, 0.0);
        }
        #[inline]
        pub fn add_width(&mut self, width: i32) {
            self.fbb_.push_slot::<i32>(CharInfo::VT_WIDTH, width, 0);
        }
        #[inline]
        pub fn add_height(&mut self, height: i32) {
            self.fbb_.push_slot::<i32>(CharInfo::VT_HEIGHT, height, 0);
        }
        #[inline]
        pub fn add_advance(&mut self, advance: i32) {
            self.fbb_.push_slot::<i32>(CharInfo::VT_ADVANCE, advance, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> CharInfoBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            CharInfoBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<CharInfo<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for CharInfo<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("CharInfo");
            ds.field("r", &self.r());
            ds.field("u1", &self.u1());
            ds.field("v1", &self.v1());
            ds.field("u2", &self.u2());
            ds.field("v2", &self.v2());
            ds.field("width", &self.width());
            ds.field("height", &self.height());
            ds.field("advance", &self.advance());
            ds.finish()
        }
    }
    pub enum InitEngineOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct InitEngine<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for InitEngine<'a> {
        type Inner = InitEngine<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> InitEngine<'a> {
        pub const VT_WIDTH: ::flatbuffers::VOffsetT = 4;
        pub const VT_HEIGHT: ::flatbuffers::VOffsetT = 6;
        pub const VT_ATLAS_WIDTH: ::flatbuffers::VOffsetT = 8;
        pub const VT_ATLAS_HEIGHT: ::flatbuffers::VOffsetT = 10;
        pub const VT_ATLAS_PIXELS: ::flatbuffers::VOffsetT = 12;
        pub const VT_CHARS: ::flatbuffers::VOffsetT = 14;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            InitEngine { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args InitEngineArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<InitEngine<'bldr>> {
            let mut builder = InitEngineBuilder::new(_fbb);
            if let Some(x) = args.chars {
                builder.add_chars(x);
            }
            if let Some(x) = args.atlas_pixels {
                builder.add_atlas_pixels(x);
            }
            builder.add_atlas_height(args.atlas_height);
            builder.add_atlas_width(args.atlas_width);
            builder.add_height(args.height);
            builder.add_width(args.width);
            builder.finish()
        }

        #[inline]
        pub fn width(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(InitEngine::VT_WIDTH, Some(0)).unwrap() }
        }
        #[inline]
        pub fn height(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<i32>(InitEngine::VT_HEIGHT, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn atlas_width(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<i32>(InitEngine::VT_ATLAS_WIDTH, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn atlas_height(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<i32>(InitEngine::VT_ATLAS_HEIGHT, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn atlas_pixels(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        InitEngine::VT_ATLAS_PIXELS,
                        None,
                    )
            }
        }
        #[inline]
        pub fn chars(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CharInfo<'a>>>>
        {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CharInfo>>,
                >>(InitEngine::VT_CHARS, None)
            }
        }
    }

    impl ::flatbuffers::Verifiable for InitEngine<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<i32>("width", Self::VT_WIDTH, false)?
                .visit_field::<i32>("height", Self::VT_HEIGHT, false)?
                .visit_field::<i32>("atlas_width", Self::VT_ATLAS_WIDTH, false)?
                .visit_field::<i32>("atlas_height", Self::VT_ATLAS_HEIGHT, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "atlas_pixels",
                    Self::VT_ATLAS_PIXELS,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<CharInfo>>,
                >>("chars", Self::VT_CHARS, false)?
                .finish();
            Ok(())
        }
    }
    pub struct InitEngineArgs<'a> {
        pub width: i32,
        pub height: i32,
        pub atlas_width: i32,
        pub atlas_height: i32,
        pub atlas_pixels: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        pub chars: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<CharInfo<'a>>>,
            >,
        >,
    }
    impl<'a> Default for InitEngineArgs<'a> {
        #[inline]
        fn default() -> Self {
            InitEngineArgs {
                width: 0,
                height: 0,
                atlas_width: 0,
                atlas_height: 0,
                atlas_pixels: None,
                chars: None,
            }
        }
    }

    pub struct InitEngineBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> InitEngineBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_width(&mut self, width: i32) {
            self.fbb_.push_slot::<i32>(InitEngine::VT_WIDTH, width, 0);
        }
        #[inline]
        pub fn add_height(&mut self, height: i32) {
            self.fbb_.push_slot::<i32>(InitEngine::VT_HEIGHT, height, 0);
        }
        #[inline]
        pub fn add_atlas_width(&mut self, atlas_width: i32) {
            self.fbb_
                .push_slot::<i32>(InitEngine::VT_ATLAS_WIDTH, atlas_width, 0);
        }
        #[inline]
        pub fn add_atlas_height(&mut self, atlas_height: i32) {
            self.fbb_
                .push_slot::<i32>(InitEngine::VT_ATLAS_HEIGHT, atlas_height, 0);
        }
        #[inline]
        pub fn add_atlas_pixels(
            &mut self,
            atlas_pixels: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                InitEngine::VT_ATLAS_PIXELS,
                atlas_pixels,
            );
        }
        #[inline]
        pub fn add_chars(
            &mut self,
            chars: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<CharInfo<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(InitEngine::VT_CHARS, chars);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> InitEngineBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            InitEngineBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<InitEngine<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for InitEngine<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("InitEngine");
            ds.field("width", &self.width());
            ds.field("height", &self.height());
            ds.field("atlas_width", &self.atlas_width());
            ds.field("atlas_height", &self.atlas_height());
            ds.field("atlas_pixels", &self.atlas_pixels());
            ds.field("chars", &self.chars());
            ds.finish()
        }
    }
    pub enum GoToRustMessageOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct GoToRustMessage<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for GoToRustMessage<'a> {
        type Inner = GoToRustMessage<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> GoToRustMessage<'a> {
        pub const VT_MESSAGE_TYPE: ::flatbuffers::VOffsetT = 4;
        pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            GoToRustMessage { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args GoToRustMessageArgs,
        ) -> ::flatbuffers::WIPOffset<GoToRustMessage<'bldr>> {
            let mut builder = GoToRustMessageBuilder::new(_fbb);
            if let Some(x) = args.message {
                builder.add_message(x);
            }
            builder.add_message_type(args.message_type);
            builder.finish()
        }

        #[inline]
        pub fn message_type(&self) -> GoToRustUnion {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<GoToRustUnion>(
                        GoToRustMessage::VT_MESSAGE_TYPE,
                        Some(GoToRustUnion::NONE),
                    )
                    .unwrap()
            }
        }
        #[inline]
        pub fn message(&self) -> Option<::flatbuffers::Table<'a>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                        GoToRustMessage::VT_MESSAGE,
                        None,
                    )
            }
        }
        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_init_engine(&self) -> Option<InitEngine<'a>> {
            if self.message_type() == GoToRustUnion::InitEngine {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { InitEngine::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_render_frame(&self) -> Option<RenderFrame<'a>> {
            if self.message_type() == GoToRustUnion::RenderFrame {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { RenderFrame::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_play_sound(&self) -> Option<PlaySound<'a>> {
            if self.message_type() == GoToRustUnion::PlaySound {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { PlaySound::init_from_table(t) }
                })
            } else {
                None
            }
        }
    }

    impl ::flatbuffers::Verifiable for GoToRustMessage<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_union::<GoToRustUnion, _>(
                    "message_type",
                    Self::VT_MESSAGE_TYPE,
                    "message",
                    Self::VT_MESSAGE,
                    false,
                    |key, v, pos| match key {
                        GoToRustUnion::InitEngine => v
                            .verify_union_variant::<::flatbuffers::ForwardsUOffset<InitEngine>>(
                                "GoToRustUnion::InitEngine",
                                pos,
                            ),
                        GoToRustUnion::RenderFrame => v
                            .verify_union_variant::<::flatbuffers::ForwardsUOffset<RenderFrame>>(
                                "GoToRustUnion::RenderFrame",
                                pos,
                            ),
                        GoToRustUnion::PlaySound => v
                            .verify_union_variant::<::flatbuffers::ForwardsUOffset<PlaySound>>(
                                "GoToRustUnion::PlaySound",
                                pos,
                            ),
                        _ => Ok(()),
                    },
                )?
                .finish();
            Ok(())
        }
    }
    pub struct GoToRustMessageArgs {
        pub message_type: GoToRustUnion,
        pub message: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    }
    impl<'a> Default for GoToRustMessageArgs {
        #[inline]
        fn default() -> Self {
            GoToRustMessageArgs {
                message_type: GoToRustUnion::NONE,
                message: None,
            }
        }
    }

    pub struct GoToRustMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GoToRustMessageBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_message_type(&mut self, message_type: GoToRustUnion) {
            self.fbb_.push_slot::<GoToRustUnion>(
                GoToRustMessage::VT_MESSAGE_TYPE,
                message_type,
                GoToRustUnion::NONE,
            );
        }
        #[inline]
        pub fn add_message(
            &mut self,
            message: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                GoToRustMessage::VT_MESSAGE,
                message,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> GoToRustMessageBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            GoToRustMessageBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<GoToRustMessage<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for GoToRustMessage<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("GoToRustMessage");
            ds.field("message_type", &self.message_type());
            match self.message_type() {
                GoToRustUnion::InitEngine => {
                    if let Some(x) = self.message_as_init_engine() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                GoToRustUnion::RenderFrame => {
                    if let Some(x) = self.message_as_render_frame() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                GoToRustUnion::PlaySound => {
                    if let Some(x) = self.message_as_play_sound() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                _ => {
                    let x: Option<()> = None;
                    ds.field("message", &x)
                }
            };
            ds.finish()
        }
    }
    pub enum EventOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Event<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for Event<'a> {
        type Inner = Event<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> Event<'a> {
        pub const VT_TYPE_: ::flatbuffers::VOffsetT = 4;
        pub const VT_X: ::flatbuffers::VOffsetT = 6;
        pub const VT_Y: ::flatbuffers::VOffsetT = 8;
        pub const VT_BUTTON: ::flatbuffers::VOffsetT = 10;
        pub const VT_DELTA: ::flatbuffers::VOffsetT = 12;
        pub const VT_KEYCODE: ::flatbuffers::VOffsetT = 14;
        pub const VT_CHAR: ::flatbuffers::VOffsetT = 16;
        pub const VT_WIDTH: ::flatbuffers::VOffsetT = 18;
        pub const VT_HEIGHT: ::flatbuffers::VOffsetT = 20;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            Event { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args EventArgs,
        ) -> ::flatbuffers::WIPOffset<Event<'bldr>> {
            let mut builder = EventBuilder::new(_fbb);
            builder.add_height(args.height);
            builder.add_width(args.width);
            builder.add_char(args.char);
            builder.add_keycode(args.keycode);
            builder.add_delta(args.delta);
            builder.add_button(args.button);
            builder.add_y(args.y);
            builder.add_x(args.x);
            builder.add_type_(args.type_);
            builder.finish()
        }

        #[inline]
        pub fn type_(&self) -> EventType {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<EventType>(Event::VT_TYPE_, Some(EventType::WindowClose))
                    .unwrap()
            }
        }
        #[inline]
        pub fn x(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(Event::VT_X, Some(0)).unwrap() }
        }
        #[inline]
        pub fn y(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(Event::VT_Y, Some(0)).unwrap() }
        }
        #[inline]
        pub fn button(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(Event::VT_BUTTON, Some(0)).unwrap() }
        }
        #[inline]
        pub fn delta(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(Event::VT_DELTA, Some(0)).unwrap() }
        }
        #[inline]
        pub fn keycode(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(Event::VT_KEYCODE, Some(0)).unwrap() }
        }
        #[inline]
        pub fn char(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(Event::VT_CHAR, Some(0)).unwrap() }
        }
        #[inline]
        pub fn width(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(Event::VT_WIDTH, Some(0)).unwrap() }
        }
        #[inline]
        pub fn height(&self) -> i32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i32>(Event::VT_HEIGHT, Some(0)).unwrap() }
        }
    }

    impl ::flatbuffers::Verifiable for Event<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<EventType>("type_", Self::VT_TYPE_, false)?
                .visit_field::<i32>("x", Self::VT_X, false)?
                .visit_field::<i32>("y", Self::VT_Y, false)?
                .visit_field::<i32>("button", Self::VT_BUTTON, false)?
                .visit_field::<i32>("delta", Self::VT_DELTA, false)?
                .visit_field::<u32>("keycode", Self::VT_KEYCODE, false)?
                .visit_field::<u32>("char", Self::VT_CHAR, false)?
                .visit_field::<i32>("width", Self::VT_WIDTH, false)?
                .visit_field::<i32>("height", Self::VT_HEIGHT, false)?
                .finish();
            Ok(())
        }
    }
    pub struct EventArgs {
        pub type_: EventType,
        pub x: i32,
        pub y: i32,
        pub button: i32,
        pub delta: i32,
        pub keycode: u32,
        pub char: u32,
        pub width: i32,
        pub height: i32,
    }
    impl<'a> Default for EventArgs {
        #[inline]
        fn default() -> Self {
            EventArgs {
                type_: EventType::WindowClose,
                x: 0,
                y: 0,
                button: 0,
                delta: 0,
                keycode: 0,
                char: 0,
                width: 0,
                height: 0,
            }
        }
    }

    pub struct EventBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EventBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_type_(&mut self, type_: EventType) {
            self.fbb_
                .push_slot::<EventType>(Event::VT_TYPE_, type_, EventType::WindowClose);
        }
        #[inline]
        pub fn add_x(&mut self, x: i32) {
            self.fbb_.push_slot::<i32>(Event::VT_X, x, 0);
        }
        #[inline]
        pub fn add_y(&mut self, y: i32) {
            self.fbb_.push_slot::<i32>(Event::VT_Y, y, 0);
        }
        #[inline]
        pub fn add_button(&mut self, button: i32) {
            self.fbb_.push_slot::<i32>(Event::VT_BUTTON, button, 0);
        }
        #[inline]
        pub fn add_delta(&mut self, delta: i32) {
            self.fbb_.push_slot::<i32>(Event::VT_DELTA, delta, 0);
        }
        #[inline]
        pub fn add_keycode(&mut self, keycode: u32) {
            self.fbb_.push_slot::<u32>(Event::VT_KEYCODE, keycode, 0);
        }
        #[inline]
        pub fn add_char(&mut self, char: u32) {
            self.fbb_.push_slot::<u32>(Event::VT_CHAR, char, 0);
        }
        #[inline]
        pub fn add_width(&mut self, width: i32) {
            self.fbb_.push_slot::<i32>(Event::VT_WIDTH, width, 0);
        }
        #[inline]
        pub fn add_height(&mut self, height: i32) {
            self.fbb_.push_slot::<i32>(Event::VT_HEIGHT, height, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> EventBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            EventBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<Event<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for Event<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("Event");
            ds.field("type_", &self.type_());
            ds.field("x", &self.x());
            ds.field("y", &self.y());
            ds.field("button", &self.button());
            ds.field("delta", &self.delta());
            ds.field("keycode", &self.keycode());
            ds.field("char", &self.char());
            ds.field("width", &self.width());
            ds.field("height", &self.height());
            ds.finish()
        }
    }
    pub enum EventBatchOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct EventBatch<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for EventBatch<'a> {
        type Inner = EventBatch<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> EventBatch<'a> {
        pub const VT_EVENTS: ::flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            EventBatch { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args EventBatchArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<EventBatch<'bldr>> {
            let mut builder = EventBatchBuilder::new(_fbb);
            if let Some(x) = args.events {
                builder.add_events(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn events(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Event<'a>>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Event>>,
                >>(EventBatch::VT_EVENTS, None)
            }
        }
    }

    impl ::flatbuffers::Verifiable for EventBatch<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Event>>,
                >>("events", Self::VT_EVENTS, false)?
                .finish();
            Ok(())
        }
    }
    pub struct EventBatchArgs<'a> {
        pub events: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Event<'a>>>,
            >,
        >,
    }
    impl<'a> Default for EventBatchArgs<'a> {
        #[inline]
        fn default() -> Self {
            EventBatchArgs { events: None }
        }
    }

    pub struct EventBatchBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> EventBatchBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_events(
            &mut self,
            events: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<Event<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(EventBatch::VT_EVENTS, events);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> EventBatchBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            EventBatchBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<EventBatch<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for EventBatch<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("EventBatch");
            ds.field("events", &self.events());
            ds.finish()
        }
    }
    pub enum RustToGoMessageOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct RustToGoMessage<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for RustToGoMessage<'a> {
        type Inner = RustToGoMessage<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> RustToGoMessage<'a> {
        pub const VT_MESSAGE_TYPE: ::flatbuffers::VOffsetT = 4;
        pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            RustToGoMessage { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args RustToGoMessageArgs,
        ) -> ::flatbuffers::WIPOffset<RustToGoMessage<'bldr>> {
            let mut builder = RustToGoMessageBuilder::new(_fbb);
            if let Some(x) = args.message {
                builder.add_message(x);
            }
            builder.add_message_type(args.message_type);
            builder.finish()
        }

        #[inline]
        pub fn message_type(&self) -> RustToGoUnion {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<RustToGoUnion>(
                        RustToGoMessage::VT_MESSAGE_TYPE,
                        Some(RustToGoUnion::NONE),
                    )
                    .unwrap()
            }
        }
        #[inline]
        pub fn message(&self) -> Option<::flatbuffers::Table<'a>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                        RustToGoMessage::VT_MESSAGE,
                        None,
                    )
            }
        }
        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_event_batch(&self) -> Option<EventBatch<'a>> {
            if self.message_type() == RustToGoUnion::EventBatch {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { EventBatch::init_from_table(t) }
                })
            } else {
                None
            }
        }
    }

    impl ::flatbuffers::Verifiable for RustToGoMessage<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_union::<RustToGoUnion, _>(
                    "message_type",
                    Self::VT_MESSAGE_TYPE,
                    "message",
                    Self::VT_MESSAGE,
                    false,
                    |key, v, pos| match key {
                        RustToGoUnion::EventBatch => v
                            .verify_union_variant::<::flatbuffers::ForwardsUOffset<EventBatch>>(
                                "RustToGoUnion::EventBatch",
                                pos,
                            ),
                        _ => Ok(()),
                    },
                )?
                .finish();
            Ok(())
        }
    }
    pub struct RustToGoMessageArgs {
        pub message_type: RustToGoUnion,
        pub message: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    }
    impl<'a> Default for RustToGoMessageArgs {
        #[inline]
        fn default() -> Self {
            RustToGoMessageArgs {
                message_type: RustToGoUnion::NONE,
                message: None,
            }
        }
    }

    pub struct RustToGoMessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RustToGoMessageBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_message_type(&mut self, message_type: RustToGoUnion) {
            self.fbb_.push_slot::<RustToGoUnion>(
                RustToGoMessage::VT_MESSAGE_TYPE,
                message_type,
                RustToGoUnion::NONE,
            );
        }
        #[inline]
        pub fn add_message(
            &mut self,
            message: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                RustToGoMessage::VT_MESSAGE,
                message,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> RustToGoMessageBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            RustToGoMessageBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<RustToGoMessage<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for RustToGoMessage<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("RustToGoMessage");
            ds.field("message_type", &self.message_type());
            match self.message_type() {
                RustToGoUnion::EventBatch => {
                    if let Some(x) = self.message_as_event_batch() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                _ => {
                    let x: Option<()> = None;
                    ds.field("message", &x)
                }
            };
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `GoToRustMessage`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_go_to_rust_message_unchecked`.
    pub fn root_as_go_to_rust_message(
        buf: &[u8],
    ) -> Result<GoToRustMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<GoToRustMessage>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `GoToRustMessage` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_go_to_rust_message_unchecked`.
    pub fn size_prefixed_root_as_go_to_rust_message(
        buf: &[u8],
    ) -> Result<GoToRustMessage<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<GoToRustMessage>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `GoToRustMessage` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_go_to_rust_message_unchecked`.
    pub fn root_as_go_to_rust_message_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<GoToRustMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<GoToRustMessage<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `GoToRustMessage` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_go_to_rust_message_unchecked`.
    pub fn size_prefixed_root_as_go_to_rust_message_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<GoToRustMessage<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<GoToRustMessage<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a GoToRustMessage and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `GoToRustMessage`.
    pub unsafe fn root_as_go_to_rust_message_unchecked(buf: &[u8]) -> GoToRustMessage<'_> {
        unsafe { ::flatbuffers::root_unchecked::<GoToRustMessage>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed GoToRustMessage and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `GoToRustMessage`.
    pub unsafe fn size_prefixed_root_as_go_to_rust_message_unchecked(
        buf: &[u8],
    ) -> GoToRustMessage<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<GoToRustMessage>(buf) }
    }
    #[inline]
    pub fn finish_go_to_rust_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<GoToRustMessage<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_go_to_rust_message_buffer<
        'a,
        'b,
        A: ::flatbuffers::Allocator + 'a,
    >(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<GoToRustMessage<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod poem
